# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BodyServices(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, service: str=None, blocks: List[str]=None):  # noqa: E501
        """BodyServices - a model defined in Swagger

        :param service: The service of this BodyServices.  # noqa: E501
        :type service: str
        :param blocks: The blocks of this BodyServices.  # noqa: E501
        :type blocks: List[str]
        """
        self.swagger_types = {
            'service': str,
            'blocks': List[str]
        }

        self.attribute_map = {
            'service': 'service',
            'blocks': 'blocks'
        }
        self._service = service
        self._blocks = blocks

    @classmethod
    def from_dict(cls, dikt) -> 'BodyServices':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_services of this BodyServices.  # noqa: E501
        :rtype: BodyServices
        """
        return util.deserialize_model(dikt, cls)

    @property
    def service(self) -> str:
        """Gets the service of this BodyServices.


        :return: The service of this BodyServices.
        :rtype: str
        """
        return self._service

    @service.setter
    def service(self, service: str):
        """Sets the service of this BodyServices.


        :param service: The service of this BodyServices.
        :type service: str
        """

        self._service = service

    @property
    def blocks(self) -> List[str]:
        """Gets the blocks of this BodyServices.


        :return: The blocks of this BodyServices.
        :rtype: List[str]
        """
        return self._blocks

    @blocks.setter
    def blocks(self, blocks: List[str]):
        """Sets the blocks of this BodyServices.


        :param blocks: The blocks of this BodyServices.
        :type blocks: List[str]
        """

        self._blocks = blocks
