# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FixedRadiusPropModelParameters(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, radius_km: float=None):  # noqa: E501
        """FixedRadiusPropModelParameters - a model defined in Swagger

        :param radius_km: The radius_km of this FixedRadiusPropModelParameters.  # noqa: E501
        :type radius_km: float
        """
        self.swagger_types = {
            'radius_km': float
        }

        self.attribute_map = {
            'radius_km': 'radiusKM'
        }
        self._radius_km = radius_km

    @classmethod
    def from_dict(cls, dikt) -> 'FixedRadiusPropModelParameters':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The fixedRadius_prop_model_parameters of this FixedRadiusPropModelParameters.  # noqa: E501
        :rtype: FixedRadiusPropModelParameters
        """
        return util.deserialize_model(dikt, cls)

    @property
    def radius_km(self) -> float:
        """Gets the radius_km of this FixedRadiusPropModelParameters.


        :return: The radius_km of this FixedRadiusPropModelParameters.
        :rtype: float
        """
        return self._radius_km

    @radius_km.setter
    def radius_km(self, radius_km: float):
        """Sets the radius_km of this FixedRadiusPropModelParameters.


        :param radius_km: The radius_km of this FixedRadiusPropModelParameters.
        :type radius_km: float
        """
        if radius_km is None:
            raise ValueError("Invalid value for `radius_km`, must not be `None`")  # noqa: E501

        self._radius_km = radius_km
